# Generated by Django 3.2.16 on 2023-06-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_follow_unique_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
    ]
